version: "3.7"
services:

  web:
    build:
      context: "."
    #user: pptruser
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    restart: always
    working_dir: /home/app/node
    environment:
      - NODE_ENV=devlopment
    volumes:
      - ./src/:/home/app/node
    ports:
      - "8081:8081"
    command: "npm run dev"
    networks:
      - backend

networks:
  backend: